#!/usr/bin/env bash
set -e

TEST_DB_NAME="$DB_NAME"_test

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE USER $DB_USER WITH PASSWORD '$DB_PASSWORD';
  CREATE DATABASE $DB_NAME OWNER $DB_USER;
  CREATE DATABASE $TEST_DB_NAME OWNER $DB_USER;
EOSQL
